"""
Django settings for pd_project project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
#from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_u)0hbypi=rnql35)$)!l7(*d5a)=p51_kage077b@#h_yq5q8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ('ALLOWED_HOSTS', cast=Csv())
# Application definition

INSTALLED_APPS = [
    'clinic.apps.ClinicConfig',
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'django_tables2'
    #'oauth2_provider',
    #'github_oauth',
    #'social.apps.django_app.default',
    #'clinic',
    #'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'pd_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['pd_project/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect', # <--
            ],
        },
    },
]

WSGI_APPLICATION = 'pd_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pddatabase',
        'USER': 'postgres',
        'PASSWORD': 'Aashu2018',
        'HOST': 'localhost',
        'PORT': '5432',

    }
}

#AUTH_USER_MODEL = 'clinic.User'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social.backends.github.GithubOAuth2',
    'social.backends.twitter.TwitterOAuth',
    #'social_auth.backends.google.GoogleOAuthBackend',
    #'social_auth.backends.google.GoogleBackend',
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    #'oauth2_login_client.backends.OAuthBackend',
    #'github_oauth.authentication.GithubOAuthentication',
)
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/



STATICFILES_DIRS = [ BASE_DIR / 'pd_project/static/']
STATIC_ROOT= BASE_DIR / 'static'
STATIC_URL = '/static/'

LOGIN_URL = '/'
LOGOUT_URL = '/'
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIAL_AUTH_GITHUB_KEY = '70f4830d004a11f86ecb'
SOCIAL_AUTH_GITHUB_SECRET = '76f958cb61a2d5c7789f58775dbed149dd308768'
"""
GITHUB_CLIENT_ID = '70f4830d004a11f86ecb'
GITHUB_CLIENT_SECRET = '76f958cb61a2d5c7789f58775dbed149dd308768'
GITHUB_REDIRECT_URI = 'http://localhost:8000/accounts/login.html'
"""
SOCIAL_AUTH_URL_NAMESPACE = 'social'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1024381235457-vdm2gm3du0tcrt071joqusmupgs2i64o.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'bWUfW_XNBIxL57HiaK2mJmp2'


SOCIAL_AUTH_TWITTER_KEY = 'sqVEId4RrXkUc0DBBCpzDIkav'
SOCIAL_AUTH_TWITTER_SECRET = 'LcWGmnnAq2nFmfsCPOiXTz8cfstbjeDQx1UPgidZIgNCPyMYKQ'

SOCIAL_AUTH_FACEBOOK_KEY = '386135722770069'
SOCIAL_AUTH_FACEBOOK_SECRET = '17362eb004f5838b98a239eeeae37101 '
